### ISSUE TITLE
Modify weapon damage according to proportion instead of adding a fixed modification value&&Add options to modify weapon attack speed

### ISSUE THREAD

**Issue by 48004800** [Sweenus/SimplySwords#36]
Different types of weapons have different damage
If you increase the basic damage of the corresponding weapon, you will find that the damage difference between sword and hammer is not big

The basic damage of weapons of different materials is different, so the damage should be allocated proportionally. For example, the damage of the hammer is twice that of the long sword, which will not cause this problem

**Comment by 48004800** [comment]
At the same time, I want to add the option to modify the weapon attack speed

**Comment by Sweenus** [comment]
I'm not sure I understand what you mean. The config gives you direct access to increase or decrease the damage as you see fit.
It also allows for you to change attack speed.

**Comment by 48004800** [comment]
Let me explain it in detail. The attack speed of the end gobber weapon is faster than that of the nether gobber, and the attack speed of the nether gobber is faster than that of the gobber. But in this mod, the attack speed of the three is the same. I hope to adjust the attack speed according to the material, but I can't do that.

**Comment by 48004800** [comment]
Let me give an example. The attack power of the iron sword is 6, and the attack power of the iron sledge hammer is 10. The attack damage gap is fixed to 4. The damage of the end gobber sword is 18 (probably not very accurate), and the damage of the end gobber hammer is only 22. The difference is very small. Due to the difference in attack speed, the end gobber hammer is almost uncompetitive.

**Comment by 48004800** [comment]
I don't know how the attack speed in the configuration file works. I want attack speed and damage to be distributed in proportion. For example, the damage of the hammer is twice that of the sword, but the attack speed is half that of the sword. In this way, such problems will not occur.

I don't know how the attack speed in the configuration file works. I want attack speed and damage to be distributed in proportion. For example, the damage of the hammer is twice that of the sword, but the attack speed is half that of the sword. In this way, such problems will not occur.

**Comment by Sweenus** [comment]
With the exception of gobber material specific attack speeds, this can all be done in the existing weapon attributes config.

The attack damage gap between hammer and sword is not fixed.
To increase the damage of all hammer type weapons, you just need to increase the value seen below:
`"greathammer_positive_damage_modifier": 4.0,`
If you wanted to adjust the attackspeed of all hammer type weapons you would change the value below:
`"greathammer_attackspeed": -3.2,`

The way the attackspeed values work is outlined in the config:
`// -- Attack Speed Modifiers -- 
// Recommended range: -1.0 to -3.7, with -1.0 being fast and -3.7 being slow `


In regards to material specific attack speed weights - I'm not sure I would want to add this. The usecase is very small, and it would lead to further config bloat if I were to do this for every mod compat material.
I'll think on it a bit.

**Comment by 48004800** [comment]
> With the exception of gobber material specific attack speeds, this can all be done in the existing weapon attributes config.
> 
> The attack damage gap between hammer and sword is not fixed. To increase the damage of all hammer type weapons, you just need to increase the value seen below: `"greathammer_positive_damage_modifier": 4.0,` If you wanted to adjust the attackspeed of all hammer type weapons you would change the value below: `"greathammer_attackspeed": -3.2,`
> 
> The way the attackspeed values work is outlined in the config: `// -- Attack Speed Modifiers -- // Recommended range: -1.0 to -3.7, with -1.0 being fast and -3.7 being slow `
> 
> In regards to material specific attack speed weights - I'm not sure I would want to add this. The usecase is very small, and it would lead to further config bloat if I were to do this for every mod compat material. I'll think on it a bit.


For the weapon damage problem, your reply shows the problem. If I increase the damage of all hammers, the damage of iron hammers will be too strong. If I don't modify it, the power of gobber hammers will be too weak

As for the modification of weapon speed, you are right. The weapon attack speed is usually not too fast. You should reconfirm the current attack speed of gobber weapons. The end gobber is the fastest, followed by nether gobber, and the gobber is the slowest.
The attack speed of sword in gobber is slightly faster than that of vanilla sword.
vanilla sword：1.6
gobber sword: 2
nether gobber: 2.2
end gobber: 2.4

**Comment by 48004800** [comment]
For the damage of different weapon types, I think it is necessary to multiply the basic damage by a modifiable factor to get the final damage.

**Comment by Sweenus** [comment]
I appreciate your elaboration, and I think I better understand your feedback now.

I'm afraid this suggestion most likely won't see implementation for the following reasons:
1. This would be a config breaking change that would affect a great many users updating from a previous version of the mod.
2. I do not see the value or need to have weapon types performing differently at different teirs. If a Greathammer is 4 damage higher than a Sword, this should be the case across all teirs - I'm not convinced a Gobber teir greathammer should arbitrarily break this trend.
3. In terms of balance, Greathammers have been quite highly performing in some large servers that I have been observing, and it's worth noting that their attack chain ends in an attack that scales x2 the damage value on the weapon tooltip.

With that said, I can see how the Gobber weapons could be improved by adopting the tiered attackspeed changes seen in the base Gobber Swords. I will test this and gauge whether the high attackspeeds are appropriate to implement.

**Comment by 48004800** [comment]
You seem to have a misunderstanding about gobber's attack speed.

The attack speed of gobber weapons I mentioned is the original weapon attack speed in gobber mod, not my own.

**Comment by Sweenus** [comment]
Multiplicative damage scaling across all weapons doesn't sound like a good idea to me.
66% higher than 16 would have a weapon hitting something like 26 damage per swing. I don't think this makes any sense from a balance perspective in Minecraft.

There is no missunderstanding regarding the attackspeed. The Gobber mod increments the sword attackspeed stat per teir, and Simply Swords doesn't. This isn't an intended inconsistency and it's something I will look at.

**Comment by 48004800** [comment]
> Multiplicative damage scaling across all weapons doesn't sound like a good idea to me. 66% higher than 16 would have a weapon hitting something like 26 damage per swing. I don't think this makes any sense from a balance perspective in Minecraft.
> 
> There is no missunderstanding regarding the attackspeed. The Gobber mod increments the sword attackspeed stat per teir, and Simply Swords doesn't. This isn't an intended inconsistency and it's something I will look at.

There is no need to increase 66%. You can modify it according to the weapon attack speed. It can be 20% or 30%. I think fixed increase cannot adapt to the changing basic data.

Many of the figures I mentioned do not mean that we should do so. For balance problems, you can use a slower attack speed. Better combat has removed the damage immunity of melee attacks.

**Comment by 48004800** [comment]
> Multiplicative damage scaling across all weapons doesn't sound like a good idea to me. 66% higher than 16 would have a weapon hitting something like 26 damage per swing. I don't think this makes any sense from a balance perspective in Minecraft.
> 
> There is no missunderstanding regarding the attackspeed. The Gobber mod increments the sword attackspeed stat per teir, and Simply Swords doesn't. This isn't an intended inconsistency and it's something I will look at.

The damage of the hammer will be much higher than that of the sword, but don't forget that the attack speed of the hammer is only half of that of the sword. The hammer can attack once, and the sword can be waved twice. 32 is greater than 26.

**Comment by 48004800** [comment]
> Multiplicative damage scaling across all weapons doesn't sound like a good idea to me. 66% higher than 16 would have a weapon hitting something like 26 damage per swing. I don't think this makes any sense from a balance perspective in Minecraft.
> 
> There is no missunderstanding regarding the attackspeed. The Gobber mod increments the sword attackspeed stat per teir, and Simply Swords doesn't. This isn't an intended inconsistency and it's something I will look at.

Well, I have never considered pvp balance. I just found that the end gobber hammer is of limited use in single-player games.

To be honest, the damage of the end gobber hammer is only 25% higher than that of the end gobber sword, but the attack speed of the sword is 100% higher than that of the hammer. Hammers are a good choice for materials with low basic damage, but are gobber end hammers really popular with PVP players?

**Comment by Sweenus** [comment]
I can certainly see where you're coming from. While it's not something I'm willing to implement into the mod itself at this stage, you could get around this limitation by creating a datapack that overrides the Better Combat attribute files being used in Simply Swords. You could then change the per swing damage multiplier for each of the gobber hammers. Here is one of the files you could replace: [gobber_greathammer.json](https://github.com/Sweenus/SimplySwords/blob/Architectury/common/src/main/resources/data/simplyswords/weapon_attributes/gobber_compat/gobber/gobber_greathammer.json)

You can find more information on how Better Combat datapacks work [here](https://github.com/ZsoltMolnarrr/BetterCombat).

Yes, the Gobber Hammers were, for a while, the highest performer for one of the larger modpack servers Simply Swords is included in.
I believe it was due to some mod enchantments scaling better on weapons with higher base damage rather than attackspeed. It's always going to vary depending on the other mods in play alongside Simply Swords.

Hopefully that datapack solution can get you the gameplay balance you're after.

**Comment by 48004800** [comment]
Thanks for reminding me, I almost forgot that I can modify it through data packets
Sorry to waste a lot of your time

**Comment by Sweenus** [comment]
Not a waste of time at all!
Whether I agree with the feedback or not, it's always much appreciated 🙂
